#!/usr/bin/env python3
"""Generate product constants from the single reviewed branding configuration."""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]


def generate() -> None:
    product = json.loads((ROOT / "macpilot/product.json").read_text())
    for key in ("PRODUCT_NAME", "BUNDLE_DISPLAY_NAME"):
        if not re.fullmatch(r"[A-Za-z][A-Za-z0-9 -]{0,63}", product[key]):
            raise ValueError(f"Invalid {key}")
    for key in ("IOS_BUNDLE_IDENTIFIER", "MACOS_BUNDLE_IDENTIFIER"):
        if not re.fullmatch(r"[A-Za-z0-9-]+(?:\.[A-Za-z0-9-]+){2,}", product[key]):
            raise ValueError(f"Invalid {key}")
    for key in ("SUPPORT_URL", "PRIVACY_URL"):
        if product[key] is not None and not product[key].startswith("https://"):
            raise ValueError(f"{key} must be null or an HTTPS URL")
    mapping = {
        "productName": "PRODUCT_NAME", "bundleDisplayName": "BUNDLE_DISPLAY_NAME",
        "appIcon": "APP_ICON", "logo": "LOGO", "supportUrl": "SUPPORT_URL",
        "privacyUrl": "PRIVACY_URL", "defaultServerPolicy": "DEFAULT_SERVER_POLICY",
    }
    lines = ["// Generated by scripts/macpilot/generate_branding.py. Edit macpilot/product.json.",
             "abstract class MacPilotBrand {"]
    for name, key in mapping.items():
        value = product[key]
        literal = json.dumps(value, ensure_ascii=False).replace("$", r"\$")
        lines.append(f"  static const {'String?' if value is None else 'String'} {name} = {literal};")
    lines.append("}\n")
    dart = ROOT / "flutter/lib/macpilot/branding.dart"
    dart.parent.mkdir(parents=True, exist_ok=True)
    dart.write_text("\n".join(lines))
    for platform, directory in (("IOS", "ios/Flutter"), ("MACOS", "macos/Runner/Configs")):
        config = ROOT / "flutter" / directory / "MacPilot.xcconfig"
        config.write_text("// Generated from macpilot/product.json.\n"
                          f"MACPILOT_PRODUCT_NAME = {product['PRODUCT_NAME']}\n"
                          f"MACPILOT_BUNDLE_DISPLAY_NAME = {product['BUNDLE_DISPLAY_NAME']}\n"
                          f"MACPILOT_BUNDLE_IDENTIFIER = {product[platform + '_BUNDLE_IDENTIFIER']}\n")


if __name__ == "__main__":
    try:
        generate()
    except (OSError, ValueError, KeyError) as error:
        raise SystemExit(f"MacPilot: branding generation failed: {error}")
