// Generated by scripts/macpilot/generate_branding.py. Edit macpilot/product.json.
abstract class MacPilotBrand {
  static const String productName = "MacPilot";
  static const String bundleDisplayName = "MacPilot";
  static const String appIcon = "assets/macpilot_icon.png";
  static const String logo = "assets/macpilot_mark.svg";
  static const String? supportUrl = null;
  static const String? privacyUrl = null;
  static const String defaultServerPolicy = "upstream-compatible";
}
